### ISSUE TITLE
PRが出せない

### ISSUE THREAD

**Issue by kentaro-omori** [kentaro-omori/Raisetech_lecture#2]
@yuta-ushijima

以下の手順でpushまで進めたところ、PR作成時に`There isn’t anything to compare. main and lecture03 are entirely different commit histories.`と表示され、PRを作成することができませんでした。
色々やったので、抜け漏れがあったり正確な流れではないかもしれませんが、覚えている範囲でやったことを書きます。

### 以降Cloud9上で実施
* https://github.com/yuta-ushijima/raisetech-live8-sample-app  
のリポジトリをクローンし、ディレクトリ移動
```
$ git clone https://github.com/yuta-ushijima/raisetech-live8-sample-app
$ cd raisetech-live8-sample-app
```

この時のターミナルの表示は`kentaro_omori:~/environment/raisetech-live8-sample-app (main) $ `となっていた。

* この状態で講義動画を見ながらサンプルアプリケーションの動作まで実施。

* ここでレクチャーごとにブランチを分けたいと思い、`lecture03`ブランチを作成
```
(main)$ git checkout -b lecture03
```

* アプリケーション動作までの流れをまとめた`Cloud9上でのサンプルアプリケーションの起動手順`と、課題の結果をまとめた`lecture03_task.md`を作成。

* 以下のリンクを参考にリモート元URLを変更
https://qiita.com/SR_midori/items/52730907c1cddeb78b4d
```
(lecture03)$ git remote set-url origin https://github.com/kentaro-omori/Raisetech_lecture
```

* git pushまでを実施
```
(lecture03)$ git add .
(lecture03)$ git commit -m "first commit"
(lecture03)$ git push origin lecture03
```

* github上でPR作成しようとすると、`There isn’t anything to compare. main and lecture03 are entirely different commit histories.`と表示されて、PR作成することができない。

今回の場合、リポジトリ自体を新規で作ってcloneした時点でリモートリポジトリのmainブランチにpushし、その後newブランチ作成してそちらで作業。  
newブランチの方に変更含んだpushをすればnewブランチからmainブランチに対してPRが出せるとは思いますが、このやり方で良いのか分かりません。

**Comment by yuta-ushijima** [comment]
@kentaro-omori 

今回の原因としては、cloneした後に既存のリポジトリに紐付けを行なった影響で、サンプルリポジトリの履歴と本リポジトリの履歴が一致しないことが理由ですね。

この場合、lecutre03ブランチでmainブランチをマージしようとすると、とあるエラーが発生します。

そのエラーメッセージをキーワードに調べてみると、解決策となる記事が出てくると思いますので、そちらを実行すればPRが作成できるようになりますよ。

ちょっと頑張って調べてみてください！

**Comment by kentaro-omori** [comment]
@yuta-ushijima 

ありがとうございます！
エラーメッセージから調べてmainにmergeすることで対処できることは把握していたのですが、mainの内容を変えず残したままでの対応ができるかを調べていたため実施していませんでした。
実際の開発ではこのような使い方はしないと思いますが、妙にこだわってしまいました。

mainにmergeすることでPRの発行ができることを確認しました。

https://github.com/kentaro-omori/Raisetech_lecture/pull/3

**Comment by yuta-ushijima** [comment]
お！mainブランチにマージできてますね！
ただ、READMEがconflictしたままマージされているようなので、余裕あればそこも直せるといいかなと！
それ以外はLGTMです！

**Comment by kentaro-omori** [comment]
ありがとうございます！
Cloud9で競合しているREADME.mdを開いたところ、どちらのファイルを使用するかを選ぶことができたので、clone元のREADME.mdを残すようにしてmainに再pushすることでconflictの解消が出来ました！

**Comment by yuta-ushijima** [comment]
いいですね！バッチリだと思います！
このIssueは解決したかと思うのでcloseしちゃいましょう！
